function RT_path_kml_out(sat,sv_pos,rcvr_pos,type,reflection,out_path)
%plot ray-tracing

R2D = 180/pi;
for idsv = 1:size(sat,1)
    sv_llh = xyz2llh(sv_pos(idsv,:));
    sv_llh = sv_llh.*[R2D,R2D,1];
    rcvr_llh = xyz2llh(rcvr_pos);
    rcvr_llh = rcvr_llh.*[R2D,R2D,1];
    inter_llh = xyz2llh(reflection(idsv,:));
    inter_llh = inter_llh.*[R2D,R2D,1];
    
    switch type(idsv)
        case 0 %NLOS
            kmlwriteline([out_path,'\PRN',num2str(sat(idsv)),'_NLOS.kml'],...
                         [sv_llh(1),rcvr_llh(1)],...
                         [sv_llh(2),rcvr_llh(2)],...
                         [sv_llh(3),rcvr_llh(3)],...
                         'Color',[.1,.1,.1],'LineWidth',3,'Name','  ');
        case 1 %LOS
            kmlwriteline([out_path,'\PRN',num2str(sat(idsv)),'_LOS.kml'],...
                         [sv_llh(1),rcvr_llh(1)],...
                         [sv_llh(2),rcvr_llh(2)],...
                         [sv_llh(3),rcvr_llh(3)],...
                         'Color','g','LineWidth',5,'Name','  ');
        case 2 %Multipath
            kmlwriteline([out_path,'\PRN',num2str(sat(idsv)),'_LOS.kml'],...
                         [sv_llh(1),rcvr_llh(1)],...
                         [sv_llh(2),rcvr_llh(2)],...
                         [sv_llh(3),rcvr_llh(3)],...
                         'Color','g','LineWidth',5,'Name','  ');
            kmlwriteline([out_path,'\PRN',num2str(sat(idsv)),'_Refl.kml'],...
                         [sv_llh(1),inter_llh(1),rcvr_llh(1)],...
                         [sv_llh(2),inter_llh(2),rcvr_llh(2)],...
                         [sv_llh(3),inter_llh(3),rcvr_llh(3)],...
                         'Color','r','LineWidth',5,'Name','  ');
        case 3
            kmlwriteline([out_path,'\PRN',num2str(sat(idsv)),'_NLOS.kml'],...
                         [sv_llh(1),rcvr_llh(1)],...
                         [sv_llh(2),rcvr_llh(2)],...
                         [sv_llh(3),rcvr_llh(3)],...
                         'Color',[.1,.1,.1],'LineWidth',3,'Name','  ');
            kmlwriteline([out_path,'\PRN',num2str(sat(idsv)),'_Refl.kml'],...
                         [sv_llh(1),inter_llh(1),rcvr_llh(1)],...
                         [sv_llh(2),inter_llh(2),rcvr_llh(2)],...
                         [sv_llh(3),inter_llh(3),rcvr_llh(3)],...
                         'Color','r','LineWidth',5,'Name','  ');
    end
    
end

